### ISSUE TITLE
why did colors disappear from npm ?

### ISSUE THREAD

**Issue by ChaitanyaNirf** [DABH/colors.js#65]
Was it removed or unpublished ?
![image](https://github.com/user-attachments/assets/948a66ee-53a1-48c6-915c-c65be60455b6)

**Comment by ChaitanyaNirf** [comment]
strange but it's back up again 
![image](https://github.com/user-attachments/assets/9042bfa7-00ae-482e-9221-5d2e4dbfe725)
Closing this issue

**Comment by DABH** [comment]
You'll want to be using the right library: https://www.npmjs.com/package/@colors/colors

**Comment by ChaitanyaNirf** [comment]
Pretty sure I was using the correct one

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@colors%2fcolors - Not found
npm ERR! 404 
npm ERR! 404  '@colors/colors@^1.6.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'winston'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.


It’s very strange, I did manually check on the npm registry and it wasn’t there…after sometime it showed up
